name: Update work item state when PR is merged

on:
   pull_request:
    branches: [master]
    types: [closed]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:       
    - uses: CanarysAutomations/pr-update-work-item-state@master
      env: 
        gh_token : '${{ secrets.GH_TOKEN }}'   
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: 'RealWorldDevelopers'
        ado_project: 'Toolbox'
        closedstate: 'Closed'
        gh_repo_owner: 'RealWorldDevelopers'
        gh_repo: 'RWD.Toolbox.Ui.Middleware'
        pull_number: '${{github.event.number}}'
